# MinGW 工具链
cmake_minimum_required(VERSION 3.20)

set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES CROSS_ARCH)
if(NOT DEFINED CROSS_ARCH OR "${CROSS_ARCH}" STREQUAL "")
    set(CROSS_ARCH "x86_64" CACHE STRING "Target Windows architecture")
endif()

# 架构映射
set(WIN_ARCH_MAP
    "x86_64=x86_64-w64-mingw32"
    "x86=i686-w64-mingw32"
)

# 查找工具链前缀
foreach(PAIR IN LISTS WIN_ARCH_MAP)
    string(REPLACE "=" ";" PAIR_LIST ${PAIR})
    list(GET PAIR_LIST 0 KEY)
    list(GET PAIR_LIST 1 VALUE)
    if("${CROSS_ARCH}" STREQUAL "${KEY}")
        set(TOOLCHAIN_PREFIX "${VALUE}")
        break()
    endif()
endforeach()

set(WINDOWS TRUE) 
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ${CROSS_ARCH})

# 编译器路径
find_program(MINGW_GCC NAMES ${TOOLCHAIN_PREFIX}-gcc REQUIRED)
find_program(MINGW_GXX NAMES ${TOOLCHAIN_PREFIX}-g++ REQUIRED)
find_program(MINGW_AR NAMES ${TOOLCHAIN_PREFIX}-ar ar REQUIRED)
find_program(MINGW_RANLIB NAMES ${TOOLCHAIN_PREFIX}-ranlib ranlib REQUIRED)
find_program(MINGW_NM NAMES ${TOOLCHAIN_PREFIX}-nm nm REQUIRED)
find_program(MINGW_STRIP NAMES ${TOOLCHAIN_PREFIX}-strip strip REQUIRED)
find_program(MINGW_WINDRES NAMES ${TOOLCHAIN_PREFIX}-windres windres REQUIRED)

# Windows交叉编译配置
set(CMAKE_C_COMPILER ${MINGW_GCC})
set(CMAKE_CXX_COMPILER ${MINGW_GXX})
set(CMAKE_RC_COMPILER ${MINGW_WINDRES})
set(CMAKE_AR ${MINGW_AR} CACHE FILEPATH "AR" FORCE)
set(CMAKE_RANLIB ${MINGW_RANLIB} CACHE FILEPATH "RANLIB" FORCE)
set(CMAKE_NM ${MINGW_NM} CACHE FILEPATH "NM" FORCE)
set(CMAKE_STRIP ${MINGW_STRIP} CACHE FILEPATH "STRIP" FORCE)
set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})

# 优化标志
set(CMAKE_C_FLAGS_RELEASE "-Os -ffunction-sections -fdata-sections")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "-Wl,--gc-sections,--exclude-libs=ALL")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)